package br.com.TADS1N.Telas;

import br.com.TADS1N.Beans.Cliente;
import br.com.TADS1N.Beans.Corretor;
import br.com.TADS1N.Beans.CorretorTableModel;
import br.com.TADS1N.Dao.ClienteDao;
import br.com.TADS1N.Dao.CorretorDao;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dougl
 */
public class telaCorretor extends javax.swing.JInternalFrame {

    private static telaCorretor instancia = null;
    Corretor corretor = new Corretor();
    CorretorDao corretorD = new CorretorDao();
    CorretorTableModel tb;
    int flag = 0;

    public telaCorretor() {
        initComponents();
        carrega();
        habilitarFormulario(false);
    }

    public static telaCorretor getInstancia() {
        if (instancia == null) {
            instancia = new telaCorretor();
        }

        return instancia;
    }

    public void carrega() {
        tb = new CorretorTableModel();
        TBL_tabelaCorretor.setModel(tb);
        List corretor = corretorD.listartodos();
        tb.setCorretor(corretor);
        TBL_tabelaCorretor.revalidate();
    }

    public void PesquisarPorCreci(String creci) {
        tb = new CorretorTableModel();
        TBL_tabelaCorretor.setModel(tb);
        List corretor = corretorD.PesquisarPorCreci(creci);
        tb.setCorretor(corretor);
        TBL_tabelaCorretor.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TXT_nome = new javax.swing.JTextField();
        TXT_creci = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_cidade = new javax.swing.JTextField();
        TXT_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_incluirCorretor = new javax.swing.JButton();
        BTN_salvarCorretor = new javax.swing.JButton();
        BTN_pesquisarCorretor = new javax.swing.JButton();
        BTN_excluirCorretor = new javax.swing.JButton();
        TXT_creciPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_tabelaCorretor = new javax.swing.JTable();
        TXT_telefone = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Corretor");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Cidade:");
        jLabel4.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel6.setText("CRECI:");
        jLabel6.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Nome:");
        jLabel1.setToolTipText("");

        TXT_nome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        TXT_creci.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Telefone:");
        jLabel3.setToolTipText("");

        TXT_cidade.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        TXT_email.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        TXT_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_emailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel5.setText("E-mail:");
        jLabel5.setToolTipText("");

        BTN_incluirCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_incluirCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Incluir_Icon.png"))); // NOI18N
        BTN_incluirCorretor.setText("Incluir");
        BTN_incluirCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_incluirCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_incluirCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_incluirCorretorActionPerformed(evt);
            }
        });

        BTN_salvarCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_salvarCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Alterar_Icon.png"))); // NOI18N
        BTN_salvarCorretor.setText("Salvar");
        BTN_salvarCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_salvarCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_salvarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salvarCorretorActionPerformed(evt);
            }
        });

        BTN_pesquisarCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_pesquisarCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Pesquisar_Icon.png"))); // NOI18N
        BTN_pesquisarCorretor.setText("Pesquisar");
        BTN_pesquisarCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_pesquisarCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_pesquisarCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_pesquisarCorretorActionPerformed(evt);
            }
        });

        BTN_excluirCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_excluirCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Excluir_Icon.png"))); // NOI18N
        BTN_excluirCorretor.setText("Excluir");
        BTN_excluirCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_excluirCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_excluirCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_excluirCorretorActionPerformed(evt);
            }
        });

        TXT_creciPesquisa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("CRECI:");
        jLabel2.setToolTipText("");

        TBL_tabelaCorretor.setBackground(new java.awt.Color(204, 204, 204));
        TBL_tabelaCorretor.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N
        TBL_tabelaCorretor.setForeground(new java.awt.Color(51, 51, 255));
        TBL_tabelaCorretor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TBL_tabelaCorretor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_tabelaCorretorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_tabelaCorretor);

        try {
            TXT_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TXT_telefone.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TXT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TXT_creci)))
                    .addComponent(jLabel5)
                    .addComponent(BTN_excluirCorretor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_creciPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_pesquisarCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTN_salvarCorretor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BTN_incluirCorretor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXT_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(TXT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(TXT_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(222, 222, 222)))))))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TXT_cidade, TXT_telefone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_creci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXT_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_incluirCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_salvarCorretor)
                    .addComponent(BTN_excluirCorretor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_creciPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BTN_pesquisarCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TXT_cidade, TXT_telefone});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_salvarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salvarCorretorActionPerformed
        if (validarFormulario()) {

            if (flag == 1) {
                corretor.setCreci(TXT_creci.getText().trim());
                corretor.setNome(TXT_nome.getText().trim());
                corretor.setTelefone(TXT_telefone.getText().trim());
                corretor.setCidade(TXT_cidade.getText().trim());
                corretor.setEmail(TXT_email.getText().trim());

                corretorD.cadastrar(corretor);
                carrega();
                JOptionPane.showMessageDialog(null, "Corretor Inserido Com  Sucesso ");
                habilitarFormulario(false);
            } else {
                if (flag == 2) {
                    corretor.setCodigo_Corretor((int) TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 0));
                    corretor.setCreci(TXT_creci.getText());
                    corretor.setNome(TXT_nome.getText());
                    corretor.setTelefone(TXT_telefone.getText());
                    corretor.setCidade(TXT_cidade.getText());
                    corretor.setEmail(TXT_email.getText());
                    corretorD.alterar(corretor);
                    JOptionPane.showMessageDialog(null, "Corretor Alterado Com  Sucesso ");
                    carrega();
                    habilitarFormulario(false);
                }
//
            }

        }


    }//GEN-LAST:event_BTN_salvarCorretorActionPerformed

    private void BTN_incluirCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_incluirCorretorActionPerformed
        flag = 1;
        habilitarFormulario(true);
    }//GEN-LAST:event_BTN_incluirCorretorActionPerformed

    private void TBL_tabelaCorretorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_tabelaCorretorMouseClicked
        // FUNÇÃO QUE SELECIONA CADA COLUNA DA TABELA  E TRAS  PARA  OS  CAMPOS 
        flag = 2;
        if (TBL_tabelaCorretor.getSelectedRow() != -1) {

            TXT_creci.setText(TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 1).toString());
            TXT_nome.setText(TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 2).toString());
            TXT_telefone.setText(TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 3).toString());
            TXT_cidade.setText(TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 4).toString());
            TXT_email.setText(TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 5).toString());
            habilitarFormulario(true);

        }


    }//GEN-LAST:event_TBL_tabelaCorretorMouseClicked

    private void BTN_excluirCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_excluirCorretorActionPerformed
        if (TBL_tabelaCorretor.getSelectedRow() != -1) {
            int confirma = JOptionPane.showConfirmDialog(this, "VC DESEJA REALMENTE EXCLUIR CORRETOR DO SEU SISTEMA ", "EXCLUIR CORRETOR", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                corretor.setCodigo_Corretor((int) TBL_tabelaCorretor.getValueAt(TBL_tabelaCorretor.getSelectedRow(), 0));
                corretorD.delete(corretor);
                carrega();
                habilitarFormulario(false);
                limpaFormulario();

            }

        }

    }//GEN-LAST:event_BTN_excluirCorretorActionPerformed

    private void TXT_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_emailActionPerformed

    private void BTN_pesquisarCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_pesquisarCorretorActionPerformed
        PesquisarPorCreci(TXT_creciPesquisa.getText());
        TXT_creciPesquisa.setText(null);
    }//GEN-LAST:event_BTN_pesquisarCorretorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_excluirCorretor;
    private javax.swing.JButton BTN_incluirCorretor;
    private javax.swing.JButton BTN_pesquisarCorretor;
    private javax.swing.JButton BTN_salvarCorretor;
    private javax.swing.JTable TBL_tabelaCorretor;
    private javax.swing.JTextField TXT_cidade;
    private javax.swing.JTextField TXT_creci;
    private javax.swing.JTextField TXT_creciPesquisa;
    private javax.swing.JTextField TXT_email;
    private javax.swing.JTextField TXT_nome;
    private javax.swing.JFormattedTextField TXT_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void habilitarFormulario(boolean ativo) {
        BTN_incluirCorretor.setEnabled(!ativo);
        BTN_salvarCorretor.setEnabled(ativo);
        BTN_excluirCorretor.setEnabled(ativo);

        TXT_nome.setEnabled(ativo);
        TXT_telefone.setEnabled(ativo);
        TXT_email.setEnabled(ativo);
        TXT_creci.setEnabled(ativo);
        TXT_cidade.setEnabled(ativo);
        TBL_tabelaCorretor.setEnabled(!ativo);

        if (!ativo) {
            limpaFormulario();
        }
    }

    private void limpaFormulario() {

        TXT_nome.setText("");
        TXT_telefone.setText("");
        TXT_email.setText("");
        TXT_creci.setText("");
        TXT_cidade.setText("");
    }

    private boolean validarFormulario() {
        if (TXT_nome.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Nome inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_nome.requestFocus();
            return false;
        }
        if (TXT_telefone.getText().trim().length() != 14) {
            JOptionPane.showMessageDialog(this, " telefone válido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_telefone.requestFocus();
            return false;
        }
        if (TXT_cidade.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, " cidade inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_cidade.requestFocus();
            return false;
        }
        if (TXT_creci.getText().trim().length() != 5) {
            JOptionPane.showMessageDialog(this, "Creci inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_creci.requestFocus();
            return false;
        }
        if (TXT_email.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, " email inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_email.requestFocus();
            return false;
        }

        return true;

    }

}
