package br.com.TADS1N.Telas;

import br.com.TADS1N.Beans.Cliente;
import br.com.TADS1N.Beans.Corretor;
import br.com.TADS1N.Beans.Imovel;
import br.com.TADS1N.Controller.ControleCliente;
import br.com.TADS1N.Dao.ClienteDao;

/**
 *
 * @author dougl
 */
public class telaPagamento extends javax.swing.JInternalFrame {

    private static telaPagamento instancia = null;

    Cliente cliente = new Cliente();
    ClienteDao clienteD = new ClienteDao();
    ControleCliente controleC = new ControleCliente();

    public telaPagamento() {
        initComponents();
    }

   
   

    public static telaPagamento getInstancia() {
        if (instancia == null) {
            instancia = new telaPagamento();
        }

        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_cpfCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT_codigoImovel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_valorImovel = new javax.swing.JTextField();
        TXT_enderecoImovel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_nome_corretor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_numeroCreci = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_nomecliente = new javax.swing.JTextField();
        BTN_salvar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pagamento");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setText("CPF do Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        TXT_cpfCliente.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        TXT_cpfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXT_cpfClienteFocusLost(evt);
            }
        });
        TXT_cpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_cpfClienteActionPerformed(evt);
            }
        });
        TXT_cpfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_cpfClienteKeyReleased(evt);
            }
        });
        getContentPane().add(TXT_cpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel4.setText("Nome do Corretor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel5.setText("Código do Imóvel:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        TXT_codigoImovel.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        TXT_codigoImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_codigoImovelActionPerformed(evt);
            }
        });
        getContentPane().add(TXT_codigoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 360, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel6.setText("Valor do Imóvel:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        TXT_valorImovel.setEditable(false);
        TXT_valorImovel.setBackground(new java.awt.Color(204, 204, 204));
        TXT_valorImovel.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        getContentPane().add(TXT_valorImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 310, 310, -1));

        TXT_enderecoImovel.setEditable(false);
        TXT_enderecoImovel.setBackground(new java.awt.Color(204, 204, 204));
        TXT_enderecoImovel.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        getContentPane().add(TXT_enderecoImovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 680, 40));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel7.setText("Endereço do Imóvel");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        TXT_nome_corretor.setEditable(false);
        getContentPane().add(TXT_nome_corretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 550, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel2.setText("NUMERO CRECI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        TXT_numeroCreci.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        TXT_numeroCreci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXT_numeroCreciFocusLost(evt);
            }
        });
        TXT_numeroCreci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_numeroCreciActionPerformed(evt);
            }
        });
        TXT_numeroCreci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_numeroCreciKeyReleased(evt);
            }
        });
        getContentPane().add(TXT_numeroCreci, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 260, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel8.setText("Nome do Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        TXT_nomecliente.setEditable(false);
        TXT_nomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_nomeclienteActionPerformed(evt);
            }
        });
        getContentPane().add(TXT_nomecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 550, 40));

        BTN_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Pagamento_Icon.png"))); // NOI18N
        getContentPane().add(BTN_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 130, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_cpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_cpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_cpfClienteActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void TXT_cpfClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXT_cpfClienteFocusLost

    }//GEN-LAST:event_TXT_cpfClienteFocusLost

    private void TXT_cpfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_cpfClienteKeyReleased
         
    }//GEN-LAST:event_TXT_cpfClienteKeyReleased

    private void TXT_numeroCreciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXT_numeroCreciFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_numeroCreciFocusLost

    private void TXT_numeroCreciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_numeroCreciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_numeroCreciActionPerformed

    private void TXT_numeroCreciKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_numeroCreciKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_numeroCreciKeyReleased

    private void TXT_nomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_nomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_nomeclienteActionPerformed

    private void TXT_codigoImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_codigoImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_codigoImovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_salvar;
    private javax.swing.JTextField TXT_codigoImovel;
    private javax.swing.JTextField TXT_cpfCliente;
    private javax.swing.JTextField TXT_enderecoImovel;
    private javax.swing.JTextField TXT_nome_corretor;
    private javax.swing.JTextField TXT_nomecliente;
    private javax.swing.JTextField TXT_numeroCreci;
    private javax.swing.JTextField TXT_valorImovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
