package br.com.TADS1N.Telas;

import br.com.TADS1N.Beans.Imovel;
import br.com.TADS1N.Beans.ImovelTableModel;
import br.com.TADS1N.Dao.ImovelDao;
import com.sun.jndi.url.iiop.iiopURLContext;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dougl
 */
public class telaImovel extends javax.swing.JInternalFrame {

    private static telaImovel instancia = null;

    Imovel imovel = new Imovel();
    ImovelDao imovelD = new ImovelDao();
    int flag = 0;
    ImovelTableModel tb;

    /**
     * Creates new form telaImovel
     */
    JTextField manipula_texto = new JTextField(40);

    public telaImovel() {
        initComponents();
        habilitarFormulario(false);
        carregar();

    }

    public void carregar() {
        tb = new ImovelTableModel();
        TBL_tabelaImovel.setModel(tb);
        List imovel = imovelD.listartodos();
        tb.setImovel(imovel);
        TBL_tabelaImovel.revalidate();

    }

    public void PesquisaPorCodigo(String codigo) {
        tb = new ImovelTableModel();
        TBL_tabelaImovel.setModel(tb);
        List imovel = imovelD.PesquisarPorCodigo(codigo);
        tb.setImovel(imovel);
        TBL_tabelaImovel.revalidate();
    }

    public static telaImovel getInstancia() {
        if (instancia == null) {
            instancia = new telaImovel();
        }

        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_endereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXT_area = new javax.swing.JTextField();
        TXT_quantidadecomodos = new javax.swing.JTextField();
        TXT_valor = new javax.swing.JTextField();
        BTN_incluirImovel = new javax.swing.JButton();
        BTN_salvarImovel = new javax.swing.JButton();
        BTN_pesquisarImovel = new javax.swing.JButton();
        BTN_excluirImovel = new javax.swing.JButton();
        TXT_codigoPesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_tabelaImovel = new javax.swing.JTable();
        txt_tipo = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Imóvel");

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setText("Endereço:");

        TXT_endereco.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        TXT_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_enderecoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel2.setText("Código:");

        TXT_codigo.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel3.setText("Área(m²):");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel4.setText("Quantidade de Cômodos:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel5.setText("Valor(R$):");

        jLabel6.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel6.setText("Tipo:");

        TXT_area.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N

        TXT_quantidadecomodos.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N

        TXT_valor.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N

        BTN_incluirImovel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_incluirImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Incluir_Icon.png"))); // NOI18N
        BTN_incluirImovel.setText("Incluir");
        BTN_incluirImovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_incluirImovel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_incluirImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_incluirImovelActionPerformed(evt);
            }
        });

        BTN_salvarImovel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_salvarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Alterar_Icon.png"))); // NOI18N
        BTN_salvarImovel.setText("Salvar");
        BTN_salvarImovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_salvarImovel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_salvarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salvarImovelActionPerformed(evt);
            }
        });

        BTN_pesquisarImovel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_pesquisarImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Pesquisar_Icon.png"))); // NOI18N
        BTN_pesquisarImovel.setText("Pesquisar");
        BTN_pesquisarImovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_pesquisarImovel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_pesquisarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_pesquisarImovelActionPerformed(evt);
            }
        });

        BTN_excluirImovel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_excluirImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/TADS1N/Telas/Excluir_Icon.png"))); // NOI18N
        BTN_excluirImovel.setText("Excluir");
        BTN_excluirImovel.setEnabled(false);
        BTN_excluirImovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_excluirImovel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_excluirImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_excluirImovelActionPerformed(evt);
            }
        });

        TXT_codigoPesquisa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel7.setText("Código:");
        jLabel7.setToolTipText("");

        TBL_tabelaImovel.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        TBL_tabelaImovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBL_tabelaImovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_tabelaImovelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TBL_tabelaImovelMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_tabelaImovel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(TXT_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TXT_area))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(TXT_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXT_quantidadecomodos)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(BTN_pesquisarImovel)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(BTN_salvarImovel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(BTN_incluirImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXT_codigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTN_excluirImovel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXT_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXT_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_quantidadecomodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_excluirImovel)
                    .addComponent(BTN_salvarImovel)
                    .addComponent(BTN_incluirImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXT_codigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_pesquisarImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_enderecoActionPerformed
        //ffff TODO add your handling code here:
    }//GEN-LAST:event_TXT_enderecoActionPerformed

    private void BTN_incluirImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_incluirImovelActionPerformed
        // metodo que libera todos os campos do formulario
        flag = 1;
        habilitarFormulario(true);
    }//GEN-LAST:event_BTN_incluirImovelActionPerformed

    private void BTN_salvarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salvarImovelActionPerformed

        if (validarFormulario()) {

            if (flag == 1) {

                imovel.setEndereco(TXT_endereco.getText());
                imovel.setCodigo(TXT_codigo.getText());
                imovel.setArea(Double.parseDouble(TXT_area.getText()));
                imovel.setValor(Double.parseDouble(TXT_valor.getText()));
                imovel.setTipo(txt_tipo.getText());
                imovel.setQuantidade_Comodo(Integer.parseInt(TXT_quantidadecomodos.getText()));

                imovelD.cadastrar(imovel);
                carregar();
                habilitarFormulario(false);

            } else {

                if (flag == 2) {
                    imovel.setId((int) TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 0));

                    imovel.setEndereco(TXT_endereco.getText());
                    imovel.setCodigo(TXT_codigo.getText());
                    imovel.setArea(Double.parseDouble(TXT_area.getText()));
                    imovel.setValor(Double.parseDouble(TXT_valor.getText()));
                    imovel.setTipo(txt_tipo.getText());
                    imovel.setQuantidade_Comodo(Integer.parseInt(TXT_quantidadecomodos.getText()));

                    imovelD.alterar(imovel);
                    carregar();
                    habilitarFormulario(false);

                }
            }
        }
    }//GEN-LAST:event_BTN_salvarImovelActionPerformed

    private void TBL_tabelaImovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_tabelaImovelMouseClicked
        flag = 2;
        if (TBL_tabelaImovel.getSelectedRow() != -1) {
            TXT_endereco.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 1).toString());
            TXT_codigo.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 2).toString());
            TXT_area.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 3).toString());
            TXT_valor.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 4).toString());
            txt_tipo.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 5).toString());
            TXT_quantidadecomodos.setText(TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 6).toString());
            habilitarFormulario(true);
            BTN_excluirImovel.setEnabled(true);
        }
    }//GEN-LAST:event_TBL_tabelaImovelMouseClicked

    private void BTN_pesquisarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_pesquisarImovelActionPerformed
        PesquisaPorCodigo(TXT_codigoPesquisa.getText());
    }//GEN-LAST:event_BTN_pesquisarImovelActionPerformed

    private void TBL_tabelaImovelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_tabelaImovelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TBL_tabelaImovelMouseEntered

    private void BTN_excluirImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_excluirImovelActionPerformed
       
        if (TBL_tabelaImovel.getSelectedRow() != -1) {
       int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir Imovel do Sistema , (Sim) - (Não)", "Excluusão", JOptionPane.YES_NO_OPTION,1);
            if (confirma == JOptionPane.YES_OPTION) {

                imovel.setId((int) TBL_tabelaImovel.getValueAt(TBL_tabelaImovel.getSelectedRow(), 0));
                 imovelD.delete(imovel);
                carregar();
                habilitarFormulario(false);
                limpaFormulario();

            }

        }
    }//GEN-LAST:event_BTN_excluirImovelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_excluirImovel;
    private javax.swing.JButton BTN_incluirImovel;
    private javax.swing.JButton BTN_pesquisarImovel;
    private javax.swing.JButton BTN_salvarImovel;
    private javax.swing.JTable TBL_tabelaImovel;
    private javax.swing.JTextField TXT_area;
    private javax.swing.JTextField TXT_codigo;
    private javax.swing.JTextField TXT_codigoPesquisa;
    private javax.swing.JTextField TXT_endereco;
    private javax.swing.JTextField TXT_quantidadecomodos;
    private javax.swing.JTextField TXT_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables

    private void habilitarFormulario(boolean ativo) {

        BTN_incluirImovel.setEnabled(!ativo);
        BTN_salvarImovel.setEnabled(ativo);

        TXT_area.setEnabled(ativo);
        TXT_codigo.setEnabled(ativo);
        TXT_endereco.setEnabled(ativo);
        TXT_quantidadecomodos.setEnabled(ativo);
        TXT_valor.setEnabled(ativo);
        txt_tipo.setEnabled(ativo);
        TBL_tabelaImovel.setEnabled(!ativo);

//        if (!ativo) {
//            limpaFormulario();
//        }
    }

    private void limpaFormulario() {

        TXT_area.setText("");
        TXT_codigo.setText("");
        TXT_endereco.setText("");
        TXT_quantidadecomodos.setText("");
        TXT_valor.setText("");
        txt_tipo.setText("");
    }

    private boolean validarFormulario() {
        if (TXT_area.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ARÉA inválido , informe a area correta", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_area.requestFocus();
            return false;
        }
        if (TXT_codigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " codigo  invalido , informe código válido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_codigo.requestFocus();
            return false;
        }
        if (TXT_endereco.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " campos endereco em branco  , informe seu endereco.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_endereco.requestFocus();
            return false;
        }
        if (TXT_quantidadecomodos.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " quantidade  se encontra vazio , informe a quantidade  inválido.", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_quantidadecomodos.requestFocus();
            return false;
        }
        if (TXT_valor.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " campo valor está em branco , informe o valor .", "Alerta", JOptionPane.WARNING_MESSAGE);
            TXT_valor.requestFocus();
            return false;
        }
        if (txt_tipo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, " campo  tipo  está em branco , informe o  tipo  .", "Alerta", JOptionPane.WARNING_MESSAGE);
            txt_tipo.requestFocus();
            return false;
        }

        return true;

    }

}
