/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author dougl
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_Cliente3 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        BTN_telaCorretor = new javax.swing.JButton();
        BTN_telaImovel = new javax.swing.JButton();
        BTN_telaClientei = new javax.swing.JButton();
        BTN_faturamenti = new javax.swing.JButton();
        BTN_pagamento = new javax.swing.JButton();
        pane = new javax.swing.JDesktopPane();

        BTN_Cliente3.setBackground(new java.awt.Color(255, 255, 255));
        BTN_Cliente3.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        BTN_Cliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Cliente_Icon.png"))); // NOI18N
        BTN_Cliente3.setText("Cliente");
        BTN_Cliente3.setToolTipText("");
        BTN_Cliente3.setBorder(null);
        BTN_Cliente3.setBorderPainted(false);
        BTN_Cliente3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Cliente3.setDefaultCapable(false);
        BTN_Cliente3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_Cliente3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_Cliente3.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_Cliente3.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_Cliente3.setName(""); // NOI18N
        BTN_Cliente3.setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Bem vindo ao iMobili!");

        BTN_telaCorretor.setBackground(new java.awt.Color(255, 255, 255));
        BTN_telaCorretor.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        BTN_telaCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Corretor_Icon.png"))); // NOI18N
        BTN_telaCorretor.setText("Corretor");
        BTN_telaCorretor.setToolTipText("");
        BTN_telaCorretor.setBorder(null);
        BTN_telaCorretor.setBorderPainted(false);
        BTN_telaCorretor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_telaCorretor.setDefaultCapable(false);
        BTN_telaCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_telaCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_telaCorretor.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_telaCorretor.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_telaCorretor.setName(""); // NOI18N
        BTN_telaCorretor.setPreferredSize(new java.awt.Dimension(240, 240));

        BTN_telaImovel.setBackground(new java.awt.Color(255, 255, 255));
        BTN_telaImovel.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        BTN_telaImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Imovel_Icon.png"))); // NOI18N
        BTN_telaImovel.setText("Imóvel");
        BTN_telaImovel.setToolTipText("");
        BTN_telaImovel.setBorder(null);
        BTN_telaImovel.setBorderPainted(false);
        BTN_telaImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_telaImovel.setDefaultCapable(false);
        BTN_telaImovel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_telaImovel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_telaImovel.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_telaImovel.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_telaImovel.setName(""); // NOI18N
        BTN_telaImovel.setPreferredSize(new java.awt.Dimension(240, 240));

        BTN_telaClientei.setBackground(new java.awt.Color(255, 255, 255));
        BTN_telaClientei.setFont(new java.awt.Font("Yu Gothic Light", 0, 48)); // NOI18N
        BTN_telaClientei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Cliente_Icon.png"))); // NOI18N
        BTN_telaClientei.setText("Cliente");
        BTN_telaClientei.setToolTipText("");
        BTN_telaClientei.setBorder(null);
        BTN_telaClientei.setBorderPainted(false);
        BTN_telaClientei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_telaClientei.setDefaultCapable(false);
        BTN_telaClientei.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_telaClientei.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_telaClientei.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_telaClientei.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_telaClientei.setName(""); // NOI18N
        BTN_telaClientei.setPreferredSize(new java.awt.Dimension(240, 240));
        BTN_telaClientei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_telaClienteiActionPerformed(evt);
            }
        });

        BTN_faturamenti.setBackground(new java.awt.Color(255, 255, 255));
        BTN_faturamenti.setFont(new java.awt.Font("Yu Gothic Light", 0, 30)); // NOI18N
        BTN_faturamenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Faturamento_Icon.png"))); // NOI18N
        BTN_faturamenti.setText("Faturamento");
        BTN_faturamenti.setToolTipText("");
        BTN_faturamenti.setBorder(null);
        BTN_faturamenti.setBorderPainted(false);
        BTN_faturamenti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_faturamenti.setDefaultCapable(false);
        BTN_faturamenti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_faturamenti.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_faturamenti.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_faturamenti.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_faturamenti.setName(""); // NOI18N
        BTN_faturamenti.setPreferredSize(new java.awt.Dimension(240, 240));

        BTN_pagamento.setBackground(new java.awt.Color(255, 255, 255));
        BTN_pagamento.setFont(new java.awt.Font("Yu Gothic Light", 0, 30)); // NOI18N
        BTN_pagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Pagamento_Icon.png"))); // NOI18N
        BTN_pagamento.setText("Pagamento");
        BTN_pagamento.setToolTipText("");
        BTN_pagamento.setBorder(null);
        BTN_pagamento.setBorderPainted(false);
        BTN_pagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_pagamento.setDefaultCapable(false);
        BTN_pagamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_pagamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BTN_pagamento.setMaximumSize(new java.awt.Dimension(240, 240));
        BTN_pagamento.setMinimumSize(new java.awt.Dimension(120, 120));
        BTN_pagamento.setName(""); // NOI18N
        BTN_pagamento.setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BTN_telaCorretor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTN_telaImovel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BTN_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN_faturamenti, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BTN_telaClientei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_telaClientei, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_telaCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_telaImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_faturamenti, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_telaClienteiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_telaClienteiActionPerformed
    if (!telaCliente.getInstancia().isVisible()) {
            pane.add(telaCliente.getInstancia());
            telaCliente.getInstancia().setVisible(true);
        } else {
            telaCliente.getInstancia().requestFocus();
        }
    }//GEN-LAST:event_BTN_telaClienteiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cliente3;
    private javax.swing.JButton BTN_faturamenti;
    private javax.swing.JButton BTN_pagamento;
    private javax.swing.JButton BTN_telaClientei;
    private javax.swing.JButton BTN_telaCorretor;
    private javax.swing.JButton BTN_telaImovel;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JDesktopPane pane;
    // End of variables declaration//GEN-END:variables
}
