/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author dougl
 */
public class telaCorretor extends javax.swing.JInternalFrame {

   private static telaCorretor instancia = null;

    /**
     * Creates new form telaCorretor
     */
    public telaCorretor() {
        initComponents();
    }

    public static telaCorretor getInstancia() {
        if (instancia == null) {
            instancia = new telaCorretor();
        }

        return instancia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TXT_nome = new javax.swing.JTextField();
        TXT_creci = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TXT_telefone = new javax.swing.JTextField();
        TXT_cidade = new javax.swing.JTextField();
        TXT_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_incluirCorretor = new javax.swing.JButton();
        BTN_salvarCorretor = new javax.swing.JButton();
        BTN_pesquisarCorretor = new javax.swing.JButton();
        BTN_excluirCorretor = new javax.swing.JButton();
        TXT_creciPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_tabelaCorretor = new javax.swing.JTable();

        setClosable(true);
        setTitle("Corretor");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Cidade:");
        jLabel4.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel6.setText("CRECI:");
        jLabel6.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Nome:");
        jLabel1.setToolTipText("");

        TXT_nome.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        TXT_creci.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Telefone:");
        jLabel3.setToolTipText("");

        TXT_telefone.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        TXT_cidade.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        TXT_email.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel5.setText("E-mail:");
        jLabel5.setToolTipText("");

        BTN_incluirCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_incluirCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Incluir_Icon.png"))); // NOI18N
        BTN_incluirCorretor.setText("Incluir");
        BTN_incluirCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_incluirCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        BTN_salvarCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_salvarCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Alterar_Icon.png"))); // NOI18N
        BTN_salvarCorretor.setText("Salvar");
        BTN_salvarCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_salvarCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        BTN_pesquisarCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_pesquisarCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Pesquisar_Icon.png"))); // NOI18N
        BTN_pesquisarCorretor.setText("Pesquisar");
        BTN_pesquisarCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_pesquisarCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        BTN_excluirCorretor.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        BTN_excluirCorretor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/Excluir_Icon.png"))); // NOI18N
        BTN_excluirCorretor.setText("Excluir");
        BTN_excluirCorretor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BTN_excluirCorretor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        TXT_creciPesquisa.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel2.setText("CRECI:");
        jLabel2.setToolTipText("");

        TBL_tabelaCorretor.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        TBL_tabelaCorretor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBL_tabelaCorretor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_email)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_creciPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_pesquisarCorretor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTN_excluirCorretor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_salvarCorretor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_incluirCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(TXT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(TXT_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TXT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_creci, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_creci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_incluirCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_salvarCorretor)
                    .addComponent(BTN_excluirCorretor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_pesquisarCorretor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_creciPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_excluirCorretor;
    private javax.swing.JButton BTN_incluirCorretor;
    private javax.swing.JButton BTN_pesquisarCorretor;
    private javax.swing.JButton BTN_salvarCorretor;
    private javax.swing.JTable TBL_tabelaCorretor;
    private javax.swing.JTextField TXT_cidade;
    private javax.swing.JTextField TXT_creci;
    private javax.swing.JTextField TXT_creciPesquisa;
    private javax.swing.JTextField TXT_email;
    private javax.swing.JTextField TXT_nome;
    private javax.swing.JTextField TXT_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
