/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.util.Arrays;

/**
 *
 * @author dougl
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_senha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        LBL_erroSenha = new javax.swing.JLabel();
        LBL_erroLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel1.setText("Nome de Usuário:");

        TXT_login.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        TXT_login.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXT_loginFocusGained(evt);
            }
        });
        TXT_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXT_loginMouseClicked(evt);
            }
        });
        TXT_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_loginActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jLabel2.setText("Senha:");

        TXT_senha.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        TXT_senha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXT_senhaFocusGained(evt);
            }
        });
        TXT_senha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXT_senhaMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        jButton1.setText("Entrar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LBL_erroSenha.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N

        LBL_erroLogin.setFont(new java.awt.Font("Yu Gothic Light", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(213, 213, 213))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_login)
                    .addComponent(LBL_erroSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LBL_erroLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXT_senha))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_erroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 47, Short.MAX_VALUE)
                .addComponent(LBL_erroSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean loginOK = false;
        boolean senhaOK = false;
        if (!"admin".equals(TXT_login.getText())) {
            if ("".equals(TXT_login.getText())) {
                LBL_erroLogin.setText("Este campo não pode ser deixado em branco!");
                LBL_erroLogin.setForeground(Color.red);
                TXT_login.setBackground(Color.pink);
            } else {
                LBL_erroLogin.setText("Nome de usuário inexistente!");
                LBL_erroLogin.setForeground(Color.red);
                TXT_login.setBackground(Color.pink);
            }
        } else {
            loginOK = true;
        }
        char[] vazio = {};
        char[] senhacerta = {'a', 'd', 'm', 'i', 'n'};
        if (!Arrays.equals(senhacerta, TXT_senha.getPassword())) {
            if (Arrays.equals(vazio, TXT_senha.getPassword())) {
                LBL_erroSenha.setText("Este campo não pode ser deixado em branco!");
                LBL_erroSenha.setForeground(Color.red);
                TXT_senha.setBackground(Color.pink);
            } else {
                LBL_erroSenha.setText("Senha inválida!");
                LBL_erroSenha.setForeground(Color.red);
                TXT_senha.setBackground(Color.pink);
            }
        } else {
            senhaOK = true;
        }

        if (loginOK == true && senhaOK == true) {
            this.setVisible(false);
            new Inicial().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXT_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_loginActionPerformed

    private void TXT_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXT_loginMouseClicked
        TXT_login.setBackground(Color.white);
        LBL_erroLogin.setText("");
    }//GEN-LAST:event_TXT_loginMouseClicked

    private void TXT_senhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXT_senhaMouseClicked
        TXT_senha.setBackground(Color.white);
        LBL_erroSenha.setText("");
    }//GEN-LAST:event_TXT_senhaMouseClicked

    private void TXT_loginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXT_loginFocusGained
        TXT_login.setBackground(Color.white);
        LBL_erroLogin.setText("");
    }//GEN-LAST:event_TXT_loginFocusGained

    private void TXT_senhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXT_senhaFocusGained
        TXT_senha.setBackground(Color.white);
        LBL_erroSenha.setText("");
    }//GEN-LAST:event_TXT_senhaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_erroLogin;
    private javax.swing.JLabel LBL_erroSenha;
    private javax.swing.JTextField TXT_login;
    private javax.swing.JPasswordField TXT_senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
